# Generated by Django 3.2.2 on 2021-05-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('flag_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oo_id', models.IntegerField(default=-1)),
                ('name', models.CharField(max_length=60)),
                ('first_name', models.CharField(max_length=60)),
                ('birth', models.DateField()),
                ('death', models.DateField()),
                ('portrait', models.URLField()),
                ('biography', models.TextField(default='')),
                ('popular', models.BooleanField(default=False)),
                ('essential', models.BooleanField(default=False)),
                ('country_ids', models.ManyToManyField(to='what.Country')),
                ('period_ids', models.ManyToManyField(to='what.Period')),
            ],
        ),
    ]
