# Generated by Django 3.2.2 on 2021-05-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('what', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composer',
            old_name='essential',
            new_name='is_essential',
        ),
        migrations.RenameField(
            model_name='composer',
            old_name='popular',
            new_name='is_popular',
        ),
    ]
