# Generated by Django 3.2.2 on 2021-05-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what', '0002_auto_20210509_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='death',
            field=models.DateField(default=None),
        ),
    ]
