# Generated by Django 3.2.2 on 2021-05-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what', '0003_alter_composer_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='death',
            field=models.DateField(default=None, null=True),
        ),
    ]
