# Generated by Django 3.2.2 on 2021-05-13 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('what', '0006_auto_20210513_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='composer',
            name='country_ids',
            field=models.ManyToManyField(blank=True, to='what.Country'),
        ),
        migrations.AlterField(
            model_name='composer',
            name='death',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='composer',
            name='period_ids',
            field=models.ManyToManyField(blank=True, to='what.Period'),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='parent_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='what.instrument'),
        ),
        migrations.AlterField(
            model_name='workversion',
            name='alt_catalogue',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workversion',
            name='alt_catalogue_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workversion',
            name='alt_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workversion',
            name='alt_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workversion',
            name='alt_tonality',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='workversion',
            name='arranger_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='what.composer'),
        ),
        migrations.AlterField(
            model_name='workversionensemble',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
