# Generated by Django 3.2.2 on 2021-05-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what', '0007_auto_20210513_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='workversion',
            name='performers_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
