# Generated by Django 3.2.2 on 2021-06-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what', '0008_workversion_performers_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['parent_id__id', 'sequence', 'id']},
        ),
        migrations.AddField(
            model_name='composer',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='work',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='key',
            field=models.CharField(blank=True, default='C', max_length=10),
        ),
        migrations.AlterField(
            model_name='workversion',
            name='performers_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
